global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'school-crm-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5000']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
